### ISSUE TITLE
Getting "User has no subscription." on models that have subscription

### ISSUE THREAD

**Issue by joshpennington** [themsaid/nova-cashier-manager#16]
I am running Cashier on a model called "Vendor". It looks like I have installed everything correctly, but when I view the resource in Nova it says "User has no subscription.".

I am wondering if I have potentially missed something in configuring the module since it is saying "User" instead of "Vendor". I set the model for Cashier inside services.php as follows

`'stripe' => [
    'model' => App\Vendor::class,
    'key' => env('STRIPE_KEY'),
    'secret' => env('STRIPE_SECRET'),
],`

I added `new \Themsaid\CashierTool\CashierTool(),` to the `tools()` function in `NovaServiceProvider` class.

I am not sure what I am missing here?

**Comment by joshpennington** [comment]
I fixed this by publishing the config file and setting the subscription name to match the product in Stripe.

**Comment by Benjyclay** [comment]
@joshpennington Which config file did you publish?

Can't see one in this package directory...

**Comment by joshpennington** [comment]
I typed `php artisan vendor:publish` and then select the Cashier Manager item from the list. The file will then appear in the config directory.

**Comment by Benjyclay** [comment]
👌 Cool, I just required the latest tag version so I couldn't see it. The master has the config in.

**Comment by jringeisen** [comment]
@joshpennington what if we have multiple subscription_names, for instance, I have a pro and annual.

**Comment by jringeisen** [comment]
@themsaid I have two subscriptions, pro and annual. Currently, the config only allows for product name. Is there anyway around this so that I can include both pro and annual?

**Comment by sa7bi** [comment]
> I fixed this by publishing the config file and setting the subscription name to match the product in Stripe.

For some reason, it does not work with me, despite putting the product name in the config file !

**Comment by mikoop79** [comment]
same for me. I have tried all possible scenarios.  Need to do a work around for multiple subscriptions.

**Comment by dajoeberlei** [comment]
> same for me. I have tried all possible scenarios. Need to do a work around for multiple subscriptions.

me too :(

**Comment by dajoeberlei** [comment]
also i found out that not the product nor the plan name or id of stripe is important in the config file.
It's the $name you give when you use:
$user->newSubscription($name, "business-yearly")
                ->create($token);

Since you can give any name there that has nothing to do with the stripe product or plan name it was a little confusing for me.
My Stripe Products are:
"standard" (with two Plans: "monthly" and "yearly")
and the same for 
"business" (with two Plans: "monthly" and "yearly")

So i named the subscription that i created a combination of those: "standard-monthly" for example.
That means i have 4 different possible subscriptions names:
"standard-monthly"
"standard-yearly"
"business-monthly"
"business-yearly"

But the config file only allows one subscription name.
Now im thinking if i name all subscriptions the same, since it seems like it doesnt matter anyway how you name them, it has nothing to do with stripe as far as i understand. (Might be wrong on this one, not sure)
But that would possible fix the issue with nova-cashier-manager

**Comment by PaulLawton227** [comment]
It's seems bizarre that this limitation is in here

I'm currently testing it now and I have 2 subscriptions:  '£10 monthly test' and '£20 monthly test' 
I put in '£10 monthly test' into the subscription_name in nova-cashier-manager config file.

Accessing my user/customer that has the subscription - under 'Manage Subscription' if the subscription is '£10 monthly test' then is shows, the '£20 monthly test' doesn't show with message: 'User has no subscription'

However, if I access the user with the 'manage' link:   /cashier-tool/user/[user_id] for each of these customers - then it shows their subscription information without being limited by the subscription_name.

Another reason why this is bizarre is that it doesn't seem to display this subscription_name from the config file anywhere??
